### ISSUE TITLE
Calc

### ISSUE THREAD

**Issue by Cruglk** [tbela99/css#42]
@tbela99, Thanks for the previous edits! ...Here We Go Again... 

Now "calc":

	$test = 'div[data-elem-id="1587819338886"] { color: #000000; z-index: 5; top: calc(50vh - 375px + 325px); left: calc(50% - 600px + 26px); width: 610px; background: red;}';

Result:

	div[data-elem-id="1587819338886"] {
	 color: #000;
	 z-index: 5;
	 top: calc(50vh- 375px+325px);
	 left: calc(50%- 600px+26px);
	 width: 610px;
	 background: red
	}

Correct:

	div[data-elem-id="1587819338886"] {
		color: #000000;
		z-index: 5;
		top: calc(50vh - 375px + 325px);
		left: calc(50% - 600px + 26px);
		width: 610px;
		background: red;
	}

**Comment by tbela99** [comment]
the issue has been fixed.

Thanks

**Comment by Cruglk** [comment]
Not sure if this is fixed. Now is:

    top: calc(50vh-375px+325px);
    left: calc(50%-600px+26px);

It should be with spaces.

    top: calc(50vh - 375px + 325px);
    left: calc(50% - 600px + 26px);

![img-2020-09-01-07-23-08](https://user-images.githubusercontent.com/18282051/91794590-1ac02800-ec24-11ea-9dc8-6646171fbfe6.png)

![img-2020-09-01-07-22-58](https://user-images.githubusercontent.com/18282051/91794586-15fb7400-ec24-11ea-83f0-00e3b35904af.png)

**Comment by tbela99** [comment]
it should be good now. sorry I missed few tests the last time

**Comment by Cruglk** [comment]
@tbela99 Thanks! But still can't download version for PHP < 7.4: https://ci.appveyor.com/project/tbela99/css/builds/34957043

**Comment by tbela99** [comment]
that is the automated test bot for PHP < 7.4. Not sure why it does not download php56. 
I will reopen the issue and add more test cases.
You can run the test locally if you have the repo on your hard drive

**Comment by tbela99** [comment]
I checked older tests for that branch and they also failed to run. I will try to fix that

**Comment by Cruglk** [comment]
@tbela99 Found another problem. This time with font and variables. Code like:

	$test = '
	:root {
		--default-font-size: 11px
	}
	.test {
		overflow-x: hidden;
		font: 400 var(--default-font-size) \'Trebuchet MS\', sans-serif;
		color: var(--color-default)
	}
	';

Problem is this:

		var(--default-font-size) \'Trebuchet MS\', sans-serif;

Like example, Its ok:

		font: 400 10px Verdana;

**Comment by tbela99** [comment]
shouldn't it be 'Trebuchet MS' instead of \'Trebuchet MS\'?

**Comment by Cruglk** [comment]
`houldn't it be 'Trebuchet MS' instead of 'Trebuchet MS'?`

The problem is only in brackets.

![2](https://user-images.githubusercontent.com/18282051/92285283-93690200-ef0c-11ea-8180-586ac6abcf06.png)


![1](https://user-images.githubusercontent.com/18282051/92285280-92d06b80-ef0c-11ea-8f71-3bfe11d98547.png)

Also:

	font: 400 16px Verdana;

After parse:


	font: 16px Verdana;

Missing "400".
![3](https://user-images.githubusercontent.com/18282051/92285412-e5118c80-ef0c-11ea-8122-f403ad2875a5.png)

**Comment by tbela99** [comment]
I mean't there should be no \\\' around Trebuchet MS but the \ got stripped

**Comment by tbela99** [comment]
I have fixed the issues you mentioned here.
I don't have the time to investigate the issue with automated test for php5.6 branch.
I can successfully run the test locally.

Thanks for reporting those issues

**Comment by tbela99** [comment]
if you want to run the tests from your cli, go to the test folder and type ./runtest.sh
